# Generated by Django 6.0.1 on 2026-02-01 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perusahaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.perusahaan')),
            ],
            options={
                'db_table': 'lowongan',
            },
        ),
    ]
