# Generated by Django 6.0.1 on 2026-02-01 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelamar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(blank=True, max_length=30, null=True)),
                ('ringkasan_profile', models.TextField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='akun.akunpengguna')),
            ],
            options={
                'db_table': 'pelamar',
            },
        ),
    ]
