

class ErrorLamaran:
    LOWONGAN_TUTUP = "LOWONGAN_TUTUP"
    DUPLIKAT_LAMARAN = "DUPLIKAT_LAMARAN"
    TIDAK_BERHAK = "TIDAK_BERHAK"
    STATUS_TIDAK_VALID = "STATUS_TIDAK_VALID"
    KEPUTUSAN_TIDAK_VALID = "KEPUTUSAN_TIDAK_VALID"
