# Generated by Django 6.0.1 on 2026-02-01 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lowongan', '0001_initial'),
        ('pelamar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('lowongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowongan.lowongan')),
                ('pelamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelamar.pelamar')),
            ],
            options={
                'db_table': 'lamaran',
                'constraints': [models.UniqueConstraint(fields=('pelamar', 'lowongan'), name='unik_pelamar_lowongan')],
            },
        ),
    ]
