# Generated by Django 6.0.1 on 2026-02-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamaran',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
